networks:
  local:
    name: local

services:
  backend:
    container_name: backend
    image: node:latest
    volumes:
      - ./:/src/
    command: bash -c "cd /src/ && make install dev-docker"
    networks:
    - local
    restart: always
    ports:
    - 3001:3001